app:
  name: Indever
  host: 0.0.0.0
  port: 8088
  debug: true
  jwt_secret: ""
  upload_dir: ./storages/uploads

database:
  driver: postgres # postgres, mysql 
  host: localhost
  port: 5432 
  database: indever
  user: postgres  # default 5432 for postgres, 3306 for mysql
  password: postgres

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

log:
  level: info
  output: file # stdout, file
  dir: ./storages/logs