app:
  name: Indever
  host: 0.0.0.0
  port: 8088
  debug: true
  jwt_secret: ""
  upload_dir: ./storages/uploads

database:
  driver: mysql # postgres, mysql, sqlite
  host: localhost
  port: 3306 
  database: indever
  user: root  # default 5432 for postgres, 3306 for mysql
  password: root
  log_level: info  # 数据库日志级别：silent, error, warn, info

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

log:
  level: info
  output: file # stdout, file
  dir: ./storages/logs