// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/zerokkcoder/indevsca/internal/app/handler"
	"github.com/zerokkcoder/indevsca/internal/domain/service"
	"github.com/zerokkcoder/indevsca/internal/infra/config"
	"github.com/zerokkcoder/indevsca/internal/infra/database"
	"github.com/zerokkcoder/indevsca/internal/repository"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp() (*App, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	databaseDatabase, err := database.New(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(databaseDatabase)
	authService := service.NewAuthService(userRepository)
	authHandler := handler.NewAuthHandler(authService)
	handlers := handler.NewHandlers(authHandler)
	app := NewApp(configConfig, handlers)
	return app, nil
}
