// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/zerokkcoder/indevsca/internal/server"
	"github.com/zerokkcoder/indevsca/pkg/app"
	"github.com/zerokkcoder/indevsca/pkg/config"
	"github.com/zerokkcoder/indevsca/pkg/log"
	"github.com/zerokkcoder/indevsca/pkg/server/http"
)

// Injectors from wire.go:

func NewWire(configConfig *config.Config, logger *log.Logger) (*app.App, func(), error) {
	httpServer := server.NewHTTPServer(logger, configConfig)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var serverSet = wire.NewSet(server.NewHTTPServer)

// build App
func newApp(
	httpServer *http.Server,

) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("demo-server"))
}
