app:
  name: Indever
  host: 0.0.0.0
  port: 8088
  mode: debug # debug, release
  debug: true
  jwt_secret: "kdjckd15664asa"
  cache: # redis

database:
  driver: mysql # postgres, mysql, sqlite
  host: localhost
  port: 3306 
  database: indever
  user: root  # default 5432 for postgres, 3306 for mysql
  password: root

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

log:
  level: info
  output: file # stdout, file
  dir: ./storages/logs